version: 2
executorType: docker
jobs:
  build:
    docker:
      - image: 352302322568.dkr.ecr.us-west-2.amazonaws.com/mm-ecs/ci-node:8.9.4.0
      - image: redis:3.2.6
    working_directory: ~/q-repeat
    steps:
      - checkout
      - restore_cache:
          key: q-repeat-full-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          command: yarn install
      - save_cache:
          key: q-repeat-full-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/q-repeat/node_modules
      - run:
          command: npm test
      - store_artifacts:
          path: ~/q-repeat/coverage
